from enum import Enum

from src.utils.color import Color

BUTTON_WIDTH = 100
BUTTON_HEIGHT = 30
NUMBER_OF_SQUARES = 50
SQUARE_SIZE = 30


FIELD_COLOR = Color.LIGHT_GRAY
BACKGROUND_COLOR = Color.DARK_GRAY
